abstract class AppConstant {
  static const String noInternet = "No hay conexión a internet";
  static const String connectionError = "Error en la conexión";
  static const String noContent = "No content";
  static const String error = "Ha ocurrido un error";
  static const String firebaseToken = "AIzaSyAFZ2uyHiPuQQi_4wf8cUQpdMEMqGapq_Q";
  static const String bearerToken =
      "eyJhbGciOiJSUzI1NiIsImtpZCI6ImY1NWU0ZDkxOGE0ODY0YWQxMzUxMDViYmRjMDEwYWY5Njc5YzM0MTMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBwbGF1ZG8tdG9kby1hcHAiLCJhdWQiOiJhcHBsYXVkby10b2RvLWFwcCIsImF1dGhfdGltZSI6MTY3MzM4MDI5NSwidXNlcl9pZCI6IllWM1BkRTRlenZkcUl3dlU5RGVFdFhXZDN4QzMiLCJzdWIiOiJZVjNQZEU0ZXp2ZHFJd3ZVOURlRXRYV2QzeEMzIiwiaWF0IjoxNjczMzgwMjk1LCJleHAiOjE2NzMzODM4OTUsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QHRlc3QuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.r44bpCRvl59ELc-9QLPQ9pNJV3ArgEFw7XfQr9NVjGXqqnw4U2oCGGYBkQO31aIu1XknJB_Lprs9JD58xkXhAkUeg4IuVDiyB0DV2FIB0GyXt4yqtdCZ7_pNlhQfsGEK0zEVlAsFNneh3qZg7GjUQvpaMKhacxjlvBs3WBgJ1pkNp_mSE0WiCciPkjHhB0VCx56laVccup9kIHFN05Bvk5byLYOQkf7ip4VfhY3vZKwbaK7LtPbRW42OL_JKnbllwGkOmT6F-8WrC0V8fmclaOjxW-MmNmhhBQxKn4KVVEWg8voNjJoHveXnDUCbahABhIgFCenbugT4r_kONQr-Jw";
}
