abstract class AppConstant {
  static const String noInternet = "No hay conexión a internet";
  static const String connectionError = "Error en la conexión";
  static const String noContent = "No content";
  static const String error = "Ha ocurrido un error";
  static const String firebaseToken = "AIzaSyAFZ2uyHiPuQQi_4wf8cUQpdMEMqGapq_Q";
  static const String bearerToken =
      "eyJhbGciOiJSUzI1NiIsImtpZCI6ImY1NWU0ZDkxOGE0ODY0YWQxMzUxMDViYmRjMDEwYWY5Njc5YzM0MTMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBwbGF1ZG8tdG9kby1hcHAiLCJhdWQiOiJhcHBsYXVkby10b2RvLWFwcCIsImF1dGhfdGltZSI6MTY3MzM3MTM0MywidXNlcl9pZCI6IllWM1BkRTRlenZkcUl3dlU5RGVFdFhXZDN4QzMiLCJzdWIiOiJZVjNQZEU0ZXp2ZHFJd3ZVOURlRXRYV2QzeEMzIiwiaWF0IjoxNjczMzcxMzQzLCJleHAiOjE2NzMzNzQ5NDMsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QHRlc3QuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.WZ1B0PlVCJZNSsqpXSoYu2AY_mErIVxo-BkwZbuz6YaYiekj2lkcrXNLqEJ0lw09KGwlo1Rk639ZjlPBJKXTecXKShdJS7g_Xq2WbFNjlRHgTf6IR27cgX2GRXQEQxDHNe-w5Nl2Ja63791a5_zqVYVEMmt2VTO2tnvcGYpVXZQlasy-lw_RYWNBzCnbSNkdX2qTKyTkxpTVslQL6aKT0G5lhpyYQC7MSIxXlwu-Vgg95EY-PlKF2RZL3CCafkuc87PTocvOYdVgxX8RvTYepN3e5GIsNwdBQxA8fjYyOi5dB8pNaByv5r1cIt8_wp9zjzYQ4_GpdFEici88adMz-Q";
}
