abstract class AppConstant {
  static const String noInternet = "No hay conexión a internet";
  static const String connectionError = "Error en la conexión";
  static const String noContent = "No content";
  static const String error = "Ha ocurrido un error";
  static const String firebaseToken = "AIzaSyAFZ2uyHiPuQQi_4wf8cUQpdMEMqGapq_Q";
  static const String bearerToken =
      "eyJhbGciOiJSUzI1NiIsImtpZCI6ImY1NWU0ZDkxOGE0ODY0YWQxMzUxMDViYmRjMDEwYWY5Njc5YzM0MTMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBwbGF1ZG8tdG9kby1hcHAiLCJhdWQiOiJhcHBsYXVkby10b2RvLWFwcCIsImF1dGhfdGltZSI6MTY3MzM3NjU3MCwidXNlcl9pZCI6IllWM1BkRTRlenZkcUl3dlU5RGVFdFhXZDN4QzMiLCJzdWIiOiJZVjNQZEU0ZXp2ZHFJd3ZVOURlRXRYV2QzeEMzIiwiaWF0IjoxNjczMzc2NTcwLCJleHAiOjE2NzMzODAxNzAsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QHRlc3QuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.qnkG5g_aiPU6MCYGDElcUxkJ8AnzYU7JHBk2jOa7STsEfZMo1M_Ne4SCOQUF2BhxI9lUv6KLKMHdvTRnynX45c4RDep8jpdVc5NUTAPgubnSdJI2VYhg5KxQZak4p_baRdR8cqIFKxUew2JzjRWz00M4PBQ9570obiqP8XlwOsdD0hIdbaS4MUbwL3UOJHCIacw_uqkS6mtHHjmXQZflJ4-ZFlvzrg5hX83lPv2tj1cA24Daro9PbQ-q1TEBEefBqMl_B0QnRGYBrdav1RRWY-Z9iT6v00dh8EOMVflSGTU9BmZz0ma5oLieKXZNed3oxQVpl-TjXqOvRszsRQsYvA";
}
